// Original filename: layout.tsx
export const metadata = {
  title: "My Awesome Site",
  description: "Generated by next + typescript + tailwindcss + sanity.io",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
