import Link from "next/link";
import "../globals.css";
import { getPages } from "../../../sanity/schemas/sanity-utils";


export const metadata = {
  title: "My Awesome Site",
  description: "Generated by next + typescript + tailwindcss + sanity.io",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-2x1 mx-auto py-16 px-24 ml-28 mr-28">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Deepak
          </Link>

          <div className="flex items-center gap-7 text-sm text-gray-600">
            {pages.map((page)=>(
              <Link key={page.slug} href={`/${page.slug}`} className="inline-block fonnt-medium hover:underline hover:translate-y-1">
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className="mt-16">{children}</main>
      </body>
    </html>
  );
}
